---
- hosts: palo_alto_pa220
  gather_facts: no

  tasks:
    - name: Gather PAN-OS facts
      paloaltonetworks.panos.panos_facts:
      register: pa_facts

    - name: Display gathered facts
      debug:
        var: pa_facts
