---
- name: Install and configure TFTP server
  hosts: all
  become: yes
  tasks:
    - name: Ensure the system is updated
      apt:
        update_cache: yes

    - name: Install TFTP server package
      apt:
        name: tftpd-hpa
        state: present

    - name: Ensure TFTP service is enabled and started
      systemd:
        name: tftpd-hpa
        enabled: yes
        state: started

    - name: Configure TFTP server
      copy:
        dest: /etc/default/tftpd-hpa
        content: |
          # /etc/default/tftpd-hpa

          TFTP_USERNAME="tftp"
          TFTP_DIRECTORY="/srv/tftp"
          TFTP_ADDRESS="0.0.0.0:69"
          TFTP_OPTIONS="--secure"
      notify:
        - restart tftpd-hpa

    - name: Create TFTP directory if it doesn't exist
      file:
        path: /srv/tftp
        state: directory
        owner: tftp
        group: tftp
        mode: '0755'

  handlers:
    - name: restart tftpd-hpa
      systemd:
        name: tftpd-hpa
        state: restarted
