---
- name: Run APT Update
  hosts: all
  become: yes  # Ensures that you have administrative privileges
  tasks:
    - name: Update APT package lists
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600  # Only update the cache if it is older than 3600 seconds (1 hour)

    - name: Check if any upgrades are available
      ansible.builtin.shell: apt list --upgradable
      register: upgradable_packages
      changed_when: false

    - name: Display upgradable packages
      ansible.builtin.debug:
        msg: "{{ upgradable_packages.stdout_lines }}"
