---
- name: Update APT package lists
  hosts: all
  become: yes
  tasks:
    - name: Remove APT lock files
      ansible.builtin.shell: rm /var/lib/apt/lists/lock /var/cache/apt/archives/lock /var/lib/dpkg/lock*
      ignore_errors: yes

    - name: Update APT package list
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Check if any upgrades are available
      ansible.builtin.shell: apt list --upgradable
      register: upgradable_packages
      changed_when: false

    - name: Display upgradable packages
      ansible.builtin.debug:
        msg: "{{ upgradable_packages.stdout_lines }}"
